name: API docs

on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|3.9|${{ hashFiles('setup.*') }}

      - name: Install ursh
        run: pip install -e .

      - name: Build API docs
        run: |
          ursh openapi export-json > openapi-spec.json
          mkdir api-docs
          npx redoc-cli bundle openapi-spec.json -o api-docs/index.html

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: api-docs
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
