name: API docs

on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Get uv cache dir
        id: uv-cache
        run: echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ${{ steps.uv-cache.outputs.dir }}
          key: uv|${{ runner.os }}|3.12|${{ hashFiles('requirements*.txt', 'pyproject.toml') }}

      - name: Install ursh
        run: uv pip install --system -e .

      - name: Build API docs
        run: |
          ursh openapi export-json > openapi-spec.json
          mkdir api-docs
          npx redoc-cli bundle openapi-spec.json -o api-docs/index.html

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: api-docs
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
